"""asldkf

Revision ID: ef93c0068cd5
Revises: 
Create Date: 2020-10-19 11:21:42.646915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef93c0068cd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slno', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slno', sa.Integer(), nullable=True),
    sa.Column('lesson', sa.Text(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('lesson', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('lessons')
    op.drop_table('chapters')
    # ### end Alembic commands ###
